### ISSUE TITLE
what does ProgressiveGrowingGAN do?

### ISSUE THREAD

**Issue by 1900zyh** [JiahuiYu/progressive_growing_of_gans_tf#5]
Thank you for your implementation of PG-GAN for tensorflow. 
I found that you have defined ProgressiveGrowingGAN, but you didn't use it. 
What does ProgressiveGrowingGAN do ?

It seems that you cannot train this network to produce 4x4 image to 1024x1024 image in an end-to-end way. You need set the "LAST_RESOLUTION" and "CURRENT_RESOLUTION" in yml file step by step, right?

**Comment by JiahuiYu** [comment]
@1900zyh Yes, you are correct. Current code is not fully polished for end-to-end training, since I have moved to other projects. Please consider use official code for progressive growing of GANs.
